### ISSUE TITLE
yujin_make workflow breaking...

### ISSUE THREAD

**Issue by asmodehn** [yujinrobot/yujin_tools#100]
After a few tests usecase with different workspaces (ROS, yujin, some devel), here is what I found out. I will simplify here in order to grab to the gist of it, and surely more accurate testing is needed.

Doing : 

- source ROS -> `PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages`
- catkin_make -> build stuff
- catkin_make run_tests -> uses current PYTHONPATH for tests + workspace as sourced from devel/setup.bash (there is some catkin_generated/cached_env.sh tricks happening there, probably mixed up with env hooks as well...)

Doing : 

- source ROS -> PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages
- yujin_make -> build stuff (with `PYTHONPATH=/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages:$PYTHONPATH`)
- back to PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages
- catkin_make run_tests -> uses current PYTHONPATH for tests  (containing workspace + ROS paths but **NOT yujin_path** ).

Note that : 
- using yujin_make for test, problem will not occur, since yujin workspace will be included **BUT current devel workspace is NOT included => tests will use binary dependencies**
- sourcing devel/setup.bash before testing will add yujin folder and problem will not occur.

=> yujin_make should either : 
1. be available only after one has sourced `/opt/yujin/amd64/indigo-devel/setup.bash` (like catkin_make). this would ensure that this is set in the python path and the catkin_make cached env.
2. somehow integrate with the catkin cached environment via some tricks, to get catkin to use the yujin workspace...

1) Seems much more suitable than 2)

This is not a blocker since there are ways to get things to work. But it can trigger problems tricky to debug, and will spend dev time until one notice the python path is not exactly what he/she expect, and that version between the workspace, the binary and the deb source is not the same.

My current culprit : rocon_python_comms (v3 in ros without connection cache, v5 in yujin with connection cache)

**Comment by stonier** [comment]
1) was one of the primary motivators for yujin_make.  Devs shouldn't have to repeatedly remember which magic underlay they had to source.  This caused many wasted hours when the right solution is having things in the cmake cache. 

Also yujin_make is intended as a replacement for catkin_make.  Extra development to support a mixed work flow is not necessary.  Use one or the other.  Let's put the dev cycles where it is important.
