### ISSUE TITLE
rosinstalls out of date

### ISSUE THREAD

**Issue by tfoote** [yujinrobot/yujin_tools#104]
The rosinstall files such as: https://raw.githubusercontent.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/turtlebot.rosinstall

Referenced from http://wiki.ros.org/action/show/turtlebot/Tutorials/indigo/Turtlebot%20Installation?action=show&redirect=turtlebot%2FTutorials%2Findigo%2FInstallation

have old branch names for several repos as reported here: http://answers.ros.org/question/188073/turtlebot-indigo-install-from-source-failing-to-get-rocon-source/?comment=245281#post-id-245281

Can we not use rosinstall_generator to avoid things like this getting out of date in the instructions?

**Comment by stonier** [comment]
i.e. use a rosinstall generator instruction in the tutorial?

**Comment by stonier** [comment]
Ach..awkward in some ways as there's a few developmental workspaces in there. I'll move to setting up the kinetic workspace like this as it's eminently more controllable.

The rosinstall for indigo and the wiki instructions are now up to date and working for indigo.
