### ISSUE TITLE
groot_sources update only update existing sources

### ISSUE THREAD

**Issue by AlexReimann** [yujinrobot/yujin_tools#105]
It currently tries to init a workspace if it can't find it.

**Comment by stonier** [comment]
Thats intentional...saves me having to remember to check if I've deleted the workspace or not.

Any cons to this?

**Comment by AlexReimann** [comment]
Unusable for everyone who doesn't have all workspaces (because no access right or don't need them)

**Comment by stonier** [comment]
It's useful for when you do a restricted target set of workspaces. The
entire permissions problem is something separate,  and admittedly awkward
without good feedback right now.

**Comment by AlexReimann** [comment]
What's useful with a restricted target set of workspaces?
Like ``groot_sources --update messages navi bootstrap gopher desktop``?

So I should just get an alias for that?

**Comment by stonier** [comment]
Got it, if there's no targets it should populate the list with what is already there.

This should also be applied to `--make`

**Comment by stonier** [comment]
Released in 0.4.43.
