### ISSUE TITLE
File "master/rosinstalls/indigo/kobuki.rosinstall" should be updated

### ISSUE THREAD

**Issue by Sunlcy** [yujinrobot/yujin_tools#111]
When I install turtlebot indigo on jetson tk1 from source and after I run this command:
`wstool init src -j5 https://raw.github.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/kobuki.rosinstall`
I get these errors:
> Exception caught during install: Error processing 'yocs_msgs' : [yocs_msgs] Checkout of https://github.com/yujinrobot/yocs_ms... version indigo into /home/ubuntu/kobuki/src/yocs_msgs failed.

> ERROR in config: Error processing 'yocs_msgs' : [yocs_msgs] Checkout of https://github.com/yujinrobot/yocs_ms... version indigo into /home/ubuntu/kobuki/src/yocs_msgs failed.
And then I know it's because the file "master/rosinstalls/indigo/kobuki.rosinstall" doesn't update in this place:
```
##############################################################################
#
# If no debs, overlay on top of the rocon and ecl rosinstallers.
#
##############################################################################

# Kobuki / Yujin stacks

- git: {local-name: yocs_msgs, version: indigo, uri: 'https://github.com/yujinrobot/yocs_msgs.git'}
... ...
```
The version should be "release/0.6-indigo" rather than "indigo" because the branch "indigo" has been removed in repository yocs_msgs.

**Comment by stonier** [comment]
Indeed, thanks for the catch. Fixed in a96bc5cd.
