### ISSUE TITLE
add option for custom source prefix to groot_sources

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_tools#48]
It would be useful, if there is a option (e.g. `--source-directoy <my_custom_directory>`) to specify a custom source directory different to `/opt/groot`.

The provided parameter would replace `/opt/groot` here:

```
###########################
# Variables
###########################

GROOT=/opt/groot
```
https://github.com/yujinrobot/yujin_tools/blob/master/scripts/groot_sources#L48

**Comment by bit-pirate** [comment]
If PR #49 is accepted, we should apply the same changes to [`groot_build`](https://github.com/yujinrobot/yujin_tools/blob/master/scripts/groot_build) as well.

Maybe also `groot_binaries`? Others?

**Comment by bit-pirate** [comment]
@stonier, if you second the implemented approach, I could add related changes in the same PR.

**Comment by stonier** [comment]
Yeah, if you want these in the other scripts go for it. You're currently the only user of this right now.
