### ISSUE TITLE
eclipse workspace dir should contain the word eclipse

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_tools#51]
I believe Eclipse's workspace settings used to be stored in a directory with a path similar to `~/eclipse/workspace/<ros_workspace_name>_<ros_workspace_name>`.

Now, the new version of yujin_tools (0.2.88) produces `~/workspace/mars/<ros_workspace_name>_<ros_workspace_name>`.

I like that the eclipse version name is now contained in this path, since the Eclipse settings may vary among version. However, it would be nice, if `eclipse` is mentioned in the path as well, since other programs and tools might use the generic `~/workspace` directory as well.

For example: `~/workspace/eclipse/mars/<ros_workspace_name>_<ros_workspace_name>`.

I'm guessing the path-creation-magic happens somewhere here: https://github.com/yujinrobot/yujin_tools/blob/master/src/yujin_tools/init_build.py#L231

**Comment by stonier** [comment]
It's actually `<ros_workspace_name>_<build_dir>` so if you're parallel building for native and arm you get `myworkspace_native` and `myworkspace_arm`. If you do like we usually do, the build dir is `.`, hence the doubling up.

Anyway, added the eclipse subdirectory there. I've actually never seen that workspace dir used by anything else and I've been using a preference built eclipse so long I've no idea if they actually do subfolder it now!

1cc020f9

0.2.90
