### ISSUE TITLE
drop somanet_msgs from gopher_bootstrap

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_tools#67]
They shouldn't be needed there.

https://github.com/yujinrobot/yujin_tools/blob/master/rosinstalls/indigo/gopher_bootstrap.rosinstall#L15

**Comment by stonier** [comment]
Can't yet - the somanet battery messages are still getting used. Tully has just pushed a new official battery message, so I'll switch over to that shortly.

**Comment by stonier** [comment]
Gone into the message workspace, so this issue is now redundant.
