### ISSUE TITLE
groot_build missing new workspaces

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_tools#70]
Missing bootstrap and desktop.. Hence they are not built.

```
REPOS=("ecto" "ecl" "navi" "rocon" "dslam" "gopher" "concert")
```
https://github.com/yujinrobot/yujin_tools/blob/master/scripts/groot_build#L54

**Comment by bit-pirate** [comment]
BTW, should does workspaces be built in a specific order. That is:

Ecto, ECL, d-SLAM, Navi, Bootstrap, Gopher, Concert, Desktop

**Comment by stonier** [comment]
Yes to your question..and in that order.
