### ISSUE TITLE
groot_sync cannot sync.

### ISSUE THREAD

**Issue by haryngod** [yujinrobot/yujin_tools#74]
when I tried groot_sync, that shown this messages.

![groot_sync launch](https://cloud.githubusercontent.com/assets/12889097/12317609/14959aa2-bad6-11e5-8d8a-87da05424bb1.png)

**Comment by stonier** [comment]
The folder moved...fixed in 93d2cdc9.

Get it in version 0.3.11+.

**Comment by stonier** [comment]
@haryngod Are you friends with god?

Can you ask him why the bastard made ice cream unhealthy for us humans?

**Comment by haryngod** [comment]
GOD answer to me, foolish people made ice-cream for their desire :D


2016-01-14 16:13 GMT+09:00 Daniel Stonier <notifications@github.com>:

> @haryngod <https://github.com/haryngod> Are you friends with god?
>
> Can you ask him why the bastard made ice cream unhealthy for us humans?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yujinrobot/yujin_tools/issues/74#issuecomment-171559404>
> .
>



-- 
=================================================
(주)유진로봇 개발본부/사원
서울특별시 금천구 가산동 345-30 남성프라자 601호
TEL 070-4657-70577 FAX 02-2104-0450
Mobile : 010-2734-5690
=================================================
