### ISSUE TITLE
yujin tools wiki: add prerequisites

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_tools#81]
For beginners it would be helpful to know, what "knowledge" prerequisites yujin tools need. That is, what does a developer need to know beforehand to fully understand what yujin tools does. I'd say this includes, but is not limited to:

* Catkin workspaces
* rosinstall
* wstool

**Comment by stonier** [comment]
Updated the overview:

*These tools are wrappers around [wstool](http://wiki.ros.org/wstool) and [catkin](http://wiki.ros.org/catkin). Having a working knowledge of how these work is essential as the yujin tools do not replace these concepts but merely simplify and extend. These wrappers simplify the catkin build process for several use cases that the fundamental tools don't support very well. This includes:*
