### ISSUE TITLE
groot_start_robot on robot

### ISSUE THREAD

**Issue by asmodehn** [yujinrobot/yujin_tools#86]
Starting groot_start_robot on robot, just because, I got error during delivery "cannot connect to move base."
So it looks like that script does not start everything on the robot...

**Comment by stonier** [comment]
Without any other robot software running?

From the binaries?

**Comment by asmodehn** [comment]
Without any other robot software running.
Only bootstrap workspace installed from what I can remember...

**Comment by stonier** [comment]
Ought to work.  Not much I can do with this unless I can see the log.

**Comment by stonier** [comment]
Closing for now.  Reopen if we try and fail again.
