### ISSUE TITLE
rviz_visual_tools needs to be installed manually

### ISSUE THREAD

**Issue by naveedhd** [yujinrobot/yujin_tools#92]
The `ros-indigo-rviz-visual-tools` had to be installed manually on the laptops.

**Comment by stonier** [comment]
Install-rosdeps didn't catch it?

**Comment by stonier** [comment]
Is it a dependency of gophee_rviz_workds?

**Comment by naveedhd** [comment]
This is a dependency of `visualise_semantics`. Since its launched from local (laptop), it needs to be installed on it. Not sure if its solved by groot_sync.

**Comment by stonier** [comment]
If it's in the package. xml depends a Groot binaries - - install-rosdeps Will catch it

**Comment by naveedhd** [comment]
It has also been observed with testing stable binaries, `tf_conversions` which is dependency of `rviz-visual-tools` were not installed and had to be installed manually.

**Comment by stonier** [comment]
It now has tf_conversions properly in the rviz visual tools package.xml so this should be resolved.
