### ISSUE TITLE
Error with groot_binaries

### ISSUE THREAD

**Issue by naveedhd** [yujinrobot/yujin_tools#96]
with `groot_binaries --devel --update`

```
ssh: Could not resolve hostname files.yujin.com: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.0]
```

**Comment by naveedhd** [comment]
It required to change IPv4 settings Method to `Automatic (Addresses Only)`

**Comment by asmodehn** [comment]
It requires the nameserver setting of your connection to be set to the DNS
server IP, when connected to yuijin network.
